### ISSUE TITLE
Sorting facet results is not reflected in SolrResult

### ISSUE THREAD

**Issue by relwell** [solrcloudpy/solrcloudpy#21]
Sorted facets are stored as a dict and are therefore not presented back to client code in the default sort order. This can be solved by using wt=python instead of JSON or by using a collections.OrdereredDict for specific fields that are sortable.

**Comment by dfdeshom** [comment]
For now, here is a work-around: pass `json.nl=arrarr` to your parameters. It will return a sorted array of facet responses, but in list format. References to the format here: http://wiki.apache.org/solr/SolJSON#JSON_specific_parameters . You'll have to use the latest from github (https://github.com/dfdeshom/solrcloudpy/commit/39155a3ba974e1e5f699e8928456d1812a4c6216) to use that feature.

**Comment by relwell** [comment]
Cleaning out my open issues.
