### ISSUE TITLE
semver 2.6.0

### ISSUE THREAD

**Issue by papachoco** [solrcloudpy/solrcloudpy#38]
Is there an ETA to update the semver dependency to the latest?

Thanks a lot

Carlos

**Comment by edrozenberg** [comment]
I second that emotion. Currently my scorched installs semver 2.7.2 and sorlpy installs 2.4.1 - running a batch upgrade on all pip items keeps oscillating between these two versions.

**Comment by relwell** [comment]
Hey folks -- sorry about missing this. I'll see about fixing that soon.

**Comment by relwell** [comment]
Added to 2.4.1 https://pypi.python.org/pypi/solrcloudpy
