### ISSUE TITLE
Add support for Kerberos Authentication

### ISSUE THREAD

**Issue by fei-cheng** [solrcloudpy/solrcloudpy#49]

**Comment by relwell** [comment]
I checked the documentation for Kerberos authentication, and it looks like we'll just need to add some support for retrieving the delegation token, keeping that in some kind of global state, and then passing it in the header of the request.

Getting Kerberos set up for testing is going to be the big challenge, so I'm happy to review a PR, but I won't be able to get to this one myself any time soon.

**Comment by fei-cheng** [comment]
I can work out a PR :). I have a local implementation, it works well in our production env.
